name: Linting
on: push

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Install node dependencies
        run: npm install
      - name: Eslint
        run: make lint
